/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 level.gltf -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    window: THREE.Mesh
    sink: THREE.Mesh
    dishWasher: THREE.Mesh
    stoveButton: THREE.Mesh
    Cube009: THREE.Mesh
    Cube009_1: THREE.Mesh
    Cube009_2: THREE.Mesh
    Cube008: THREE.Mesh
    Cube008_1: THREE.Mesh
    ovenElement: THREE.Mesh
    stool001: THREE.Mesh
    stool002: THREE.Mesh
    floor: THREE.Mesh
    Plane007: THREE.Mesh
    Plane007_1: THREE.Mesh
    knobs: THREE.Mesh
    Cube006: THREE.Mesh
    Cube006_1: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder_1: THREE.Mesh
    Plane: THREE.Mesh
    Plane_1: THREE.Mesh
    cuttingBoard: THREE.Mesh
    Plane003: THREE.Mesh
    Plane003_1: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder001_1: THREE.Mesh
  }
  materials: {
    counterTop: THREE.MeshStandardMaterial
    metallic: THREE.MeshStandardMaterial
    button: THREE.MeshStandardMaterial
    iron: THREE.MeshStandardMaterial
    metallic_01: THREE.MeshStandardMaterial
    stool: THREE.MeshStandardMaterial
    floor: THREE.MeshStandardMaterial
    counter: THREE.MeshStandardMaterial
    copper: THREE.MeshStandardMaterial
  }
}

type ActionName = 'stoveButtonAction' | 'ovenDoorAction'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/level.gltf') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="window" geometry={nodes.window.geometry} material={materials.counterTop} position={[0, 3.95, -8.21]} rotation={[0, 0, -Math.PI]} scale={[-2.57, -1.36, -0.24]} />
        <mesh name="sink" geometry={nodes.sink.geometry} material={materials.metallic} position={[0, 1.31, -6.97]} scale={[13.12, 1.21, 1]} />
        <mesh name="dishWasher" geometry={nodes.dishWasher.geometry} material={materials.metallic} position={[0, 1.31, -6.97]} scale={[13.12, 1.21, 1]} />
        <mesh name="stoveButton" geometry={nodes.stoveButton.geometry} material={materials.button} position={[-6.24, 2.54, 0.27]} scale={[13.12, 1.21, 1]} />
        <group name="oven" position={[-7, 2.13, -0.99]} scale={[13.12, 1.21, 1]}>
          <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials.metallic} />
          <mesh name="Cube009_1" geometry={nodes.Cube009_1.geometry} material={materials.iron} />
          <mesh name="Cube009_2" geometry={nodes.Cube009_2.geometry} material={materials.metallic_01} />
        </group>
        <group name="ovenDoor" position={[-6.09, 0.39, -1.07]} scale={[13.12, 1.21, 1]}>
          <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials.metallic} />
          <mesh name="Cube008_1" geometry={nodes.Cube008_1.geometry} material={materials.metallic_01} />
        </group>
        <mesh name="ovenElement" geometry={nodes.ovenElement.geometry} material={materials.iron} position={[-7.04, 0.58, -1.07]} scale={[1, 2, 1.55]} />
        <mesh name="stool001" geometry={nodes.stool001.geometry} material={materials.stool} position={[6.86, 1.05, -0.28]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.52, -0.08, -0.39]} />
        <mesh name="stool002" geometry={nodes.stool002.geometry} material={materials.stool} position={[7.16, 1.07, -3.86]} rotation={[Math.PI, -0.44, Math.PI]} scale={[-0.52, -0.08, -0.39]} />
        <mesh name="floor" geometry={nodes.floor.geometry} material={materials.floor} position={[0, 0, 2.45]} rotation={[-Math.PI, 0, -Math.PI]} scale={[8.03, 0.07, 10.38]} />
        <group name="counters" rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.03}>
          <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials.counterTop} />
          <mesh name="Plane007_1" geometry={nodes.Plane007_1.geometry} material={materials.counter} />
        </group>
        <mesh name="knobs" geometry={nodes.knobs.geometry} material={materials.metallic_01} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.03} />
        <group name="magStrip" position={[-8.01, 4.79, -1.09]} scale={[0.02, 0.1, 1.52]}>
          <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials.metallic} />
          <mesh name="Cube006_1" geometry={nodes.Cube006_1.geometry} material={materials.iron} />
        </group>
        <group name="pan" position={[-7.9, 3.42, -0.21]} rotation={[0, 0, -1.54]} scale={[0.33, 0.27, 0.33]}>
          <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials.metallic} />
          <mesh name="Cylinder_1" geometry={nodes.Cylinder_1.geometry} material={materials.copper} />
        </group>
        <group name="knifeBig" position={[-7.96, 4.53, -1.18]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={[0.84, 0.39, 0.08]}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.metallic} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.floor} />
        </group>
        <mesh name="cuttingBoard" geometry={nodes.cuttingBoard.geometry} material={materials.floor} position={[-7.91, 3.92, -2.04]} rotation={[0, 0, -Math.PI / 2]} scale={[0.6, 0.36, 0.47]} />
        <group name="knifeSmall" position={[-7.96, 4.68, -0.89]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={[0.58, 0.27, 0.05]}>
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.metallic} />
          <mesh name="Plane003_1" geometry={nodes.Plane003_1.geometry} material={materials.floor} />
        </group>
        <group name="pot" position={[-7.48, 3.04, -1.84]} rotation={[Math.PI, -0.77, -3.13]} scale={[0.22, 0.18, 0.22]}>
          <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials.metallic} />
          <mesh name="Cylinder001_1" geometry={nodes.Cylinder001_1.geometry} material={materials.copper} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/level.gltf')
